name: sodam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Gugi
      fonts:
      - asset: assets\fonts\Gugi-Regular.ttf
      
    - family: PoorStory
      fonts:
      - asset: assets\fonts\PoorStory-Regular.ttf

    - family: IBMPlexSansBold
      fonts:
      - asset: assets\fonts\IBMPlexSans-Bold.ttf

    - family: IBMPlexSansRegular
      fonts:
      - asset: assets\fonts\IBMPlexSans-Regular.ttf

    - family: IBMPlexSansSemiBold
      fonts:
      - asset: assets\fonts\IBMPlexSans-SemiBold.ttf
