name: sodam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  day_night_time_picker: ^1.3.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_tts: ^4.0.2
  http: ^1.2.2
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Gugi
      fonts:
        - asset: lib/assets/fonts/Gugi-Regular.ttf  
    - family: PoorStory
      fonts:
        - asset: lib/assets/fonts/PoorStory-Regular.ttf
    - family: IBMPlexSansKRBold
      fonts:
        - asset: lib/assets/fonts/IBMPlexSansKR-Bold.ttf
    - family: IBMPlexSansKRRegular
      fonts:
        - asset: lib/assets/fonts/IBMPlexSansKR-Regular.ttf
    - family: IBMPlexSansKRLight
      fonts:
        - asset: lib/assets/fonts/IBMPlexSansKR-Light.ttf
    - family: DoHyeon
      fonts:
        - asset: lib/assets/fonts/Dohyeon-Regular.ttf



