// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1r4QgVsZm7O2ifJWNJebR31dsOQ2hpQ',
    appId: '1:394915139454:web:b603c39de9fc4dfbbe6d2f',
    messagingSenderId: '394915139454',
    projectId: 'sodam-2c951',
    authDomain: 'sodam-2c951.firebaseapp.com',
    storageBucket: 'sodam-2c951.firebasestorage.app',
    measurementId: 'G-F98VL6NZY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgibeVVw1oV_CFMS7f0-H0gK__KHpi6Dg',
    appId: '1:394915139454:android:24b1b362c41f295bbe6d2f',
    messagingSenderId: '394915139454',
    projectId: 'sodam-2c951',
    storageBucket: 'sodam-2c951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBznR2GBank4neuEIW93yLOUjFNU40N2GY',
    appId: '1:394915139454:ios:c71f7c800939e6f4be6d2f',
    messagingSenderId: '394915139454',
    projectId: 'sodam-2c951',
    storageBucket: 'sodam-2c951.firebasestorage.app',
    iosBundleId: 'com.example.sodam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBznR2GBank4neuEIW93yLOUjFNU40N2GY',
    appId: '1:394915139454:ios:c71f7c800939e6f4be6d2f',
    messagingSenderId: '394915139454',
    projectId: 'sodam-2c951',
    storageBucket: 'sodam-2c951.firebasestorage.app',
    iosBundleId: 'com.example.sodam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo1r4QgVsZm7O2ifJWNJebR31dsOQ2hpQ',
    appId: '1:394915139454:web:2f47c8aa82142042be6d2f',
    messagingSenderId: '394915139454',
    projectId: 'sodam-2c951',
    authDomain: 'sodam-2c951.firebaseapp.com',
    storageBucket: 'sodam-2c951.firebasestorage.app',
    measurementId: 'G-FRX9FQ9DZR',
  );
}
